### ISSUE TITLE
Validate incoming data

### ISSUE THREAD

**Issue by TPausL** [shelf-mate/backend#16]
And return where exactly the error is. For example when the name is missing return that to the frontend so that an error can be shown on exact the right spot.

**Comment by TPausL** [comment]
{message: "error blb al las"
data: {
errors: ["name", "categoryId"]
}
}

**Comment by TPausL** [comment]
In which commit was that done @RaulFilip16?

**Comment by RaulFilip16** [comment]
ErrorHandling
