### ISSUE TITLE
 Related Objects Not Being Fetched in Prisma Query

### ISSUE THREAD

**Issue by MiikkasGIT** [shelf-mate/backend#18]
When retrieving products for example with getAllProducts() we are using the prisma findMany() method but the related objects (category, unit, storage) are not being returned as objects. Instead, only the foreign key IDs (categoryId, unitId, storageId) are included in the response. When you use findMany() with no additional options in prisma it will only retrieve the data directly associated with the model, not any related objects by default.
We have to include them like this:
include: {
      category: true,
      unit: true,  
      storage: true,
    },

**Comment by TPausL** [comment]
yep that's what i meant with this one (https://github.com/shelf-mate/backend/issues/17). Allow the "include" in the service and then default it to all true, for every db request
