### ISSUE TITLE
get products by unit.

### ISSUE THREAD

**Issue by TPausL** [shelf-mate/backend#22]
see shelf-mate/api-client-ts#7

makes sense to have the request, even it is a bit weird to see everything that is measured in gramms

**Comment by MiikkasGIT** [comment]
> see [shelf-mate/api-client-ts#7](https://github.com/shelf-mate/api-client-ts/issues/7)
> 
> makes sense to have the request, even it is a bit weird to see everything that is measured in gramms

We need this request to delete all products associated with the unit before deleting the unit itself.

**Comment by TPausL** [comment]
Ah yeah I see. Now it makes a lot more sense

**Comment by RaulFilip16** [comment]
Done! Review just in case
